
import 'package:flutter/widgets.dart';


class SpilllIcons {
  SpilllIcons._();

  static const String assetsAppIcon = 'assets/app_icon.png';
  static const String assetsIconsSpilllIcons = 'assets/icons/SpilllIcons.ttf';
  static const String assetsSplashLogo = 'assets/splash_logo.png';
  static const String iconsAddImage = 'assets/icons/add-image.svg';
  static const String iconsBell = 'assets/icons/bell.svg';
  static const String iconsBellFilled = 'assets/icons/bell-filled.svg';
  static const String iconsBlock = 'assets/icons/block.svg';
  static const String iconsBulb = 'assets/icons/bulb.svg';
  static const String iconsCheckThickRounded = 'assets/icons/check-thick-rounded.svg';
  static const String iconsCheckmark = 'assets/icons/checkmark.svg';
  static const String iconsChevronRight = 'assets/icons/chevron-right.svg';
  static const String iconsCircleMinus = 'assets/icons/circle-minus.svg';
  static const String iconsCirclePlus = 'assets/icons/circle-plus.svg';
  static const String iconsCopyLinkRounded = 'assets/icons/copy-link-rounded.svg';
  static const String iconsDelete = 'assets/icons/delete.svg';
  static const String iconsDice = 'assets/icons/dice.svg';
  static const String iconsDirectionArrowFilled = 'assets/icons/direction-arrow-filled.svg';
  static const String iconsFlag  = 'assets/icons/flag.svg';
  static const String iconsFriendColoredCircular = 'assets/icons/friend-colored-circular.svg';
  static const String iconsGoBack = 'assets/icons/go-back.svg';
  static const String iconsGoNext = 'assets/icons/go-next.svg';
  static const String iconsGraph = 'assets/icons/graph.svg';
  static const String iconsGraphFilled = 'assets/icons/graph-filled.svg';
  static const String iconsHashtag = 'assets/icons/hashtag.svg';
  static const String iconsHeart = 'assets/icons/heart.svg';
  static const String iconsHeartColoredCircular = 'assets/icons/heart-colored-circular.svg';
  static const String iconsHome = 'assets/icons/home.svg';
  static const String iconsHomeFilled = 'assets/icons/home-filled.svg';
  static const String iconsIgReelRounded = 'assets/icons/ig-reel-rounded.svg';
  static const String iconsIgRounded = 'assets/icons/ig-rounded.svg';
  static const String iconsIgStoriesRounded = 'assets/icons/ig-stories-rounded.svg';
  static const String iconsInstagram = 'assets/icons/instagram.svg';
  static const String iconsLegal = 'assets/icons/legal.svg';
  static const String iconsLink = 'assets/icons/link.svg';
  static const String iconsLinkThick = 'assets/icons/link-thick.svg';
  static const String iconsLinkedin = 'assets/icons/linkedin.svg';
  static const String iconsLinkedinRounded = 'assets/icons/linkedin-rounded.svg';
  static const String iconsLogout = 'assets/icons/logout.svg';
  static const String iconsMapPin = 'assets/icons/map-pin.svg';
  static const String iconsMapPinFilled = 'assets/icons/map-pin-filled.svg';
  static const String iconsMessengerRounded = 'assets/icons/messenger-rounded.svg';
  static const String iconsMic = 'assets/icons/mic.svg';
  static const String iconsPencil = 'assets/icons/pencil.svg';
  static const String iconsPlay = 'assets/icons/play.svg';
  static const String iconsPlayColoredCircular = 'assets/icons/play-colored-circular.svg';
  static const String iconsPlayFilled = 'assets/icons/play-filled.svg';
  static const String iconsPlusThick = 'assets/icons/plus-thick.svg';
  static const String iconsRedditRounded = 'assets/icons/reddit-rounded.svg';
  static const String iconsReply = 'assets/icons/reply.svg';
  static const String iconsReplyColoredCircular = 'assets/icons/reply-colored-circular.svg';
  static const String iconsSearch = 'assets/icons/search.svg';
  static const String iconsSettingsGear = 'assets/icons/settings-gear.svg';
  static const String iconsShare = 'assets/icons/share.svg';
  static const String iconsShareArrowDown = 'assets/icons/share-arrow-down.svg';
  static const String iconsShieldCheck = 'assets/icons/shield-check.svg';
  static const String iconsSnapchatRounded = 'assets/icons/snapchat-rounded.svg';
  static const String iconsSparkleColoredCircular = 'assets/icons/sparkle-colored-circular.svg';
  static const String iconsSpilllIcons = 'assets/icons/SpilllIcons.ttf';
  static const String iconsThreadsRounded = 'assets/icons/threads-rounded.svg';
  static const String iconsThreeDotMenu = 'assets/icons/three-dot-menu.svg';
  static const String iconsTrend = 'assets/icons/trend.svg';
  static const String iconsTrendColoredCircular = 'assets/icons/trend-colored-circular.svg';
  static const String iconsTrendFilled = 'assets/icons/trend-filled.svg';
  static const String iconsTwitter = 'assets/icons/twitter.svg';
  static const String iconsUnlock = 'assets/icons/unlock.svg';
  static const String iconsVolumeFull = 'assets/icons/volume-full.svg';
  static const String iconsVolumeMute = 'assets/icons/volume-mute.svg';
  static const String iconsWhatsappRounded = 'assets/icons/whatsapp-rounded.svg';
  static const String iconsXRounded = 'assets/icons/x-rounded.svg';
}
